version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.15.3
  aws-ecs: circleci/aws-ecs@2.1.0
jobs:
  build_production_api_server:
    working_directory: ~/app
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          create-repo: false
          dockerfile: Dockerfile
          region: AWS_REGION_ENV_VAR_NAME
          repo: foodrun-node-api
          skip-when-tags-exist: false
          tag: "${CIRCLE_SHA1}"
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_production_api_server:
          filters:
            branches:
              only:
                - master
      - aws-ecs/deploy-service-update:
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          aws-region: AWS_REGION_ENV_VAR_NAME
          cluster-name: "food-runner-ecs-node"
          container-image-name-updates: "container=food-run-container,tag=${CIRCLE_SHA1}"
          family: "food-run-task-definition"
          service-name: "food-run-ecs-service"
          requires:
            - build_staging_api_server
          filters:
            branches:
              only:
                - master